USE codeup_test_db;
TRUNCATE albums;
INSERT INTO albums (artist, name, release_date, sales, genre)
VALUES ('Michael Jackson', 'Thriller', '1982', 50.2, 'Pop'),
       ('AC/DC', 'Back in Black', '1980', 30.1, 'Hard Rock'),
       ('Whitney Houston', 'The Bodyguard', 1992, 28.7, 'R&B'),
       ('Eagles', 'Their Greatest Hits', 1976, 41.2, 'Country Rock'),
       ('Pink Floyd', 'The Dark Side of the Moon', '1973', 24.8, 'Progressive Rock'),
       ('Eagles', 'Hotel California', '1976', 31.8, 'Soft Rock'),
       ('Shania Twain', 'Come On Over', '1997', 29.9, 'Country'),
       ('Fleetwood Mac', 'Rumors', '1977', 29.3, 'Soft Rock'),
       ('Bee Gees ', 'Saturday Night Fever', '1977', 22.6, 'Disco'),
       ('John Travolta', 'Grease: The Original Soundtrack from the Motion Picture', '1978', 14.4, 'Rock'),
       ('Led Zeppelin', 'Led Zeppelin IV', '1971', 30.4, 'Hard Rock'),
       ('Michael Jackson', 'Bad', 1987, 21.1, 'Pop'),
       ('Alanis Morissette', 'Jagged Little Pill', '1995', 25.3, 'Alternative Rock'),
       ('Celine Dion', 'Falling into You', 1996, 21.1, 'Pop'),
       ('The Beatles', 'Sgt. Peppers Lonely Hearts Club Band', '1967', 18.3, 'Rock'),
       ('Patrick Swazy', 'Dirty Dancing', '1987', 17.9, 'Pop'),
       ('Michael Jackson', 'Dangerous', '1991', 17.0, 'Pop'),
       ('Adele', '21', '2011', 27.1, 'Pop'),
       ('The Beatles', '1', 2000, 23.2, 'Rock'),
       ('Metallica', 'Metallica', '1991', 22.7, 'Heavy Metal'),
       ('Celine Dion', 'Let''s Talk About Love', '2000', 19.5, 'Pop'),
       ('The Beatles', 'Abbey Road', '1969', 16.8, 'Rock'),
       ('Guns N'' Roses', 'Appetite for Destruction', '1987', 22.8, 'Hard Rock'),
       ('Bruce Springsteen', 'Born in the U.S.A', '1984', 22, 'Heartland Rock'),
       ('Meat Loaf', 'Bat Out of Hell', '1977', 22, 'Hard Rock'),
       ('ABBA', 'Gold: Greatest Hits', '1992', 21, 'Pop'),
       ('Dire Straits', 'Brothers in Arms', '1985', 20.8, 'Roots Rock'),
       ('Santana', 'Supernatural', '1999', 20.8, 'Latin Rock'),
       ('Madonna', 'The immaculate Collection', '1990', 19.5, 'Pop'),
       ('Pink Floyd', 'The Wall', '1979', 18.9, 'Progressive Rock'),
       ('James Horner', 'Titanic: Music from the Motion Picture', '1997', 18.1, 'Film Score'),
       ('Nirvana', 'Nevermind', '1991', 17.5, 'Grunge');

SELECT * FROM albums;